title: Duncan Hart - Cyber Security & Systems Thinking Specialist
description:  The personal website of Duncan Hart, senior technology risk, cyber security & systems thinking specialist.
content: Hello, how are you? I'm <a href="https://linkedin.com/in/duncanhart">Duncan Hart</a>, it's good to meet you. I'm a senior risk, cyber security & systems thinking specialist. I have significant experience in multiple industries and multiple geographies - from in depth engineering to Board-level management. I'm the Founder and Managing Partner of <a href="https://cyberriskquant.com">Cyber Risk Quant</a>, a specialist in cyber security risk and performance measurement. I also develop pro-actively secure web applications at <a href="https://appliedopenbsd.com">Applied OpenBSD</a>, as well instant messaging for tough network environments at <a href="https://xmpp.partners">XMPP Partners</a>. I have a great passion for the paintings of L.S. Lowry. 
social:
  - platform: Mastodon
    url: https://mastodon.duncanhart.com/@duncanhart
  - platform: Twitter
    url: https://twitter.com/duncanhart
  - platform: XMPP
    url: xmpp:dah@xmpp.partners
  - platform: LinkedIn
    url: https://linkedin.com/in/duncanhart
  - platform: Schedule a meeting
    url: https://cal.com/duncanhart
  - platform: Microblog
    url: https://micro.duncanhart.com
# General settings
url: https://duncanhart.com/
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
title: Duncan Hart
description: The personal website of Duncan Hart, senior technology risk, cyber security & systems thinking specialist.
author: Duncan Hart  
# baseurl: "" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-132810913-1" # google analytics tracking
#### LAYOUT OPTIONS #####
# Half layout
half_side: right
# Full layout
full_text_position: right # left, right or center
