title: Duncan Hart

description:  The personal website of Duncan Hart, senior technology risk and cyber security specialist.

content: I'm <a href="https://linkedin.com/in/duncanhart">Duncan Hart</a> and I'm a senior risk and cybersecurity specialist. I have significant experience in multiple industries and multiple geographies - from in depth engineering to Board-level management. 

social:
  - platform: Mastodon
    url: https://mastodon.neophili.ac/@duncanhart
  - platform: Twitter
    url: https://twitter.com/duncanhart
  - platform: Email
    url: mailto:dah@duncanhart.com
  - platform: Matrix
    url: @dah:matrix.crq.ac/
# General settings
# url: http://duncanhart.com/
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
