# Your Name or Company
title: Duncan Hart

# Description of your website. This is used for social sharing.
description:  The personal website of Duncan Hart, senior technology risk and cyber security specialist.

# A brief blurb about yourself
content: Blah blah blah.

# Add your social links
social:
  - platform: github
    url: https://github.com/
  - platform: facebook
    url: https://facebook.com/
  - platform: twitter
    url: https://twitter.com/
  - platform: linkedin
    url: brianmaierjr

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
