title: Duncan Hart - Cyber Security & Systems Thinking Specialist
description:  The personal website of Duncan Hart, senior technology risk, cyber security & systems thinking specialist.
content: Hello, how are you? I'm <a href="https://linkedin.com/in/duncanhart">Duncan Hart</a> a senior risk, cyber security & systems thinking specialist. I have significant experience in multiple industries and multiple geographies - from in depth engineering to Board-level management. 
social:
  - platform: Fediverse / Mastodon
    url: https://mastodon.neophili.ac/@duncanhart
  - platform: Twitter
    url: https://twitter.com/duncanhart
  - platform: XMPP
    url: xmpp:dah@xmpp.partners
  - platform: RSS
    url: https://duncanhart.com/feed.xml
# General settings
url: https://duncanhart.com/
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
title: Duncan Hart
description: The personal website of Duncan Hart, senior technology risk, cyber security & systems thinking specialist.
author: Duncan Hart  
# baseurl: "" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-132810913-1" # google analytics tracking
#### LAYOUT OPTIONS #####
# Half layout
half_side: right
# Full layout
full_text_position: right # left, right or center
