# Your Name or Company
title: Duncan Hart

# Description of your website. This is used for social sharing.
description:  The personal website of Duncan Hart, senior technology risk and cyber security specialist.

# A brief blurb about yourself
content: I'm <a href="https://linkedin.com/in/duncanhart">Duncan Hart</a> and I'm a senior risk and cybersecurity specialist.
I have significant experience in multiple industries and multiple geographies - from in depth engineering to Board-level management. I'm also a postgraduate alumni of <a href="https://www.royalholloway.ac.uk/research-and-teaching/departments-and-schools/information-security/">The Information Security Group</a>, <a href="https://royalholloway.ac.uk/"> Royal Holloway</a>, <a href="https://london.ac.uk/"> University of London</a></span>. See my <a href="https://linkedin.com/in/duncanhart">LinkedIn profile</a> for my career history.

I microblog at <a href="https://mastodon.neophili.ac/@duncanhart"> mastodon.neophili.ac</a> and cross-post to <a href="https://twitter.com/duncanhart"> @duncanhart</a>. On <a href="https://matrix.org/"> Matrix</a> I'm <a href="https://matrix.crq.ac"> @dah:matrix.crq.ac</a>.

I'm the Chief Cyber Security Risk Quant and Managing Partner at <a href="https://www.CyberRiskQuant.com">Cyber Risk Quant</a>, a specialist in quantitative cyber security risk assessment. I also do secure systems research and development at <a href="https://AppliedOpenBSD.com">Applied OpenBSD</a>. You can also find me at <a href="https://XMPP.PARTNERS">XMPP Partners</a> where we specialise in secure messaging for low bandwidth, high latency and intermittent communication networks. You can instant message me at <a href="xmpp:dah@xmpp.partners">dah@xmpp.partners</a>.

In my spare time I'm an amateur meteorologist and you can check my local weather at <a href="https://ToorakWeather.com">Toorak Weather</a>. I also maintain a primary, stratum 1, time server using <a href="http://openntpd.org">OpenNTPD</a>.


# Add your social links
social:
  - platform: github
    url: https://github.com/
  - platform: facebook
    url: https://facebook.com/
  - platform: twitter
    url: https://twitter.com/
  - platform: linkedin
    url: brianmaierjr

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
